/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Piano(props) {
  const { nodes, materials } = useGLTF("/yamahagrandpiano.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO1.geometry}
        material={materials.Bronze}
        position={[0.5, -0.46, 0.33]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO2.geometry}
        material={materials.Bronze}
        position={[0.57, -0.24, 1.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO3.geometry}
        material={materials.Strings}
        position={[3.67, 3.17, -3.17]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO4.geometry}
        material={materials.Bronze}
        position={[0.18, -0.24, 1.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO5.geometry}
        material={materials.Interior}
        position={[-2.86, 2.62, 1.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO6.geometry}
        material={materials.Strings}
        position={[0.2, 3.24, -3.43]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO8.geometry}
        material={materials.Bronze}
        position={[-2.37, -0.61, 0.64]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO9.geometry}
        material={materials.Bronze}
        position={[-0.88, -0.61, -4.76]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO12.geometry}
        material={materials.Bronze}
        position={[3.38, -0.61, 0.64]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO13.geometry}
        material={materials.Bronze}
        position={[0.95, -0.24, 1.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO14.geometry}
        material={materials.Bronze}
        position={[0.58, -0.09, -0.43]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO15.geometry}
        material={materials["Piano Base"]}
        position={[3.91, 3.74, -1.57]}
        rotation={[1.65, -0.84, -1.53]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO16.geometry}
        material={materials["Piano Base"]}
        position={[-2.85, 2.57, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO17.geometry}
        material={materials.Bronze}
        position={[0.95, -0.09, -0.43]}
        rotation={[Math.PI / 2, -0.17, Math.PI / 2]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO18.geometry}
        material={materials.Bronze}
        position={[0.19, -0.09, -0.43]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO20.geometry}
        material={materials["Piano Base"]}
        position={[-2.73, 3.89, 1.23]}
        rotation={[Math.PI / 2, 0.64, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO21.geometry}
        material={materials["White Keys"]}
        position={[2.03, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO22.geometry}
        material={materials["White Keys"]}
        position={[-2.84, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO23.geometry}
        material={materials["Black Keys"]}
        position={[-1.78, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO24.geometry}
        material={materials["White Keys"]}
        position={[3.01, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO25.geometry}
        material={materials["White Keys"]}
        position={[-0.89, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO26.geometry}
        material={materials["Black Keys"]}
        position={[-0.8, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO27.geometry}
        material={materials["Black Keys"]}
        position={[0.17, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO28.geometry}
        material={materials["White Keys"]}
        position={[0.08, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO29.geometry}
        material={materials["Black Keys"]}
        position={[-2.75, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO30.geometry}
        material={materials["Black Keys"]}
        position={[3.1, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO31.geometry}
        material={materials["White Keys"]}
        position={[1.06, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO32.geometry}
        material={materials["Black Keys"]}
        position={[2.12, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO33.geometry}
        material={materials["White Keys"]}
        position={[-1.87, 2.63, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO34.geometry}
        material={materials["Black Keys"]}
        position={[1.15, 2.63, 0.86]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO35.geometry}
        material={materials.Bronze}
        position={[-2.83, 3.82, -1.02]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO35001.geometry}
        material={materials.Bronze}
        position={[-2.83, 3.82, -3.52]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO36.geometry}
        material={materials.Bronze}
        position={[-2.84, 3.77, -1.22]}
        rotation={[Math.PI / 2, 0.64, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NAUO36001.geometry}
        material={materials.Bronze}
        position={[-2.84, 3.77, -3.72]}
        rotation={[Math.PI / 2, 0.64, 0]}
        scale={12.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.YAMAHA.geometry}
        material={materials.Bronze}
        position={[0.22, 2.92, 0.19]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.18}
      />
    </group>
  );
}

useGLTF.preload("/yamahagrandpiano.glb");