/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Player(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/player.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions.playing)
    if (props.isPlaying) {
      actions?.playing.play()
    } else {
      actions?.playing.reset();
    }
  }, [props.isPlaying])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="CharacterArmature"
          position={[0.11, -0.42, 0.26]}
          rotation={[-0.21, 0.16, 0.15]}
        >
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Character"
            geometry={nodes.Character.geometry}
            material={materials["WomanPinkDressMaterial.002"]}
            skeleton={nodes.Character.skeleton}
          />
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials["WomanPinkDressMaterial.002"]}
            skeleton={nodes.Hair.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/player.glb");