/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, PositionalAudio } from "@react-three/drei";

export function Player({clicked, isPlaying, ...props}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/player.glb");
  const { actions } = useAnimations(animations, group);
  const audio = useRef();

  const startPlaying = () => {
    console.log("Player.jsx: audio playing..");
    audio.current.stop();
    audio.current.play();
    actions?.playing.play();
  }

  const stopPlaying = () => {
    console.log("Player.jsx: audio stopping..");
    audio.current.stop();
    actions?.playing.stop();
  }

  useEffect(() => {
    console.log(`Player.jsx: playing is ${isPlaying}`)
    if (!audio.current) {
      return;
    }

    if (isPlaying) {
      startPlaying();
    } else {
      stopPlaying();
    }
  }, [isPlaying])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="CharacterArmature"
          position={[0.11, -0.42, 0.26]}
          rotation={[-0.21, 0.16, 0.15]}
        >
          <PositionalAudio
            url="sounds/chopin.mp3"
            distance={5}
            loop
            autoplay
            ref={audio}
          />
          
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Character"
            geometry={nodes.Character.geometry}
            material={materials["WomanPinkDressMaterial.002"]}
            skeleton={nodes.Character.skeleton}
          />
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials["WomanPinkDressMaterial.002"]}
            skeleton={nodes.Hair.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/player.glb");